// Auto generated by generator

module cache_debug_mux(
    $input_ports,
    input[$$clog2($cache_cnt)-1:0] sel,
    output reg[$out_width-1:0] cnt_o);
    always@(*)
        case(sel)
            $selects;
            default: cnt_o <= 0;
        endcase
endmodule
